FROM golang:latest
LABEL maintainer="aashrayanand01@gmail.com"
RUN go get github.com/AashrayAnand/Distributed-Slow-Loris/broadcaster
CMD ["echo", "usage: broadcaster --endpoint <url> --threads <# of threads> --delay <delay between writes>"]
